[build]
  command = "pnpm install && CI=false pnpm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "8"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
